# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 1

onlyLabels: [old-issue]

# Issues with these labels will never be considered stale. Set to `[]` to disable
# We don't close any issue that is an enhancement or confirmed bug, but issues
# waiting for reproduction cases and questions tend to get outdated.

# Label to use when marking as stale
staleLabel: "waiting-reply"

# Comment to post when marking as stale. Set to `false` to disable
markComment: false

# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false

# Comment to post when closing a stale Issue. Set to `false` to disable
closeComment: >
  This issue was reported on a version of Consul that is quite old.
  Based on the volume of changes since that version we encourage you to try reproducing with the latest version of Consul. 
  If you feel the issue is critical and on an older version of Consul, or still exists in the current version, 
  do feel free to let us know and we can re-open it.
  
  
  Thank you for your initial report, and again, do feel free to ask us to re-open or create a new issue, 
  and be sure to include the suggested debugging information in the issue template.
  
# Limit to only `issues`
only: issues

